### ISSUE TITLE
why doesn't the code work by SHOT?

### ISSUE THREAD

**Issue by WangdongZhao99** [mohamedr002/MAPU_SFDA_TS#1]
I want to reproduce this result.But when I tried SHOT , it made this mistake that hparams cant find SHOT.
this code does not contain SHOT?

**Comment by mohamedr002** [comment]
Hi, yes, the current code only includes the MAPU method. However, I will edit it accordingly to include SHOT method, thanking for raising this issue

**Comment by mohamedr002** [comment]
Hi, I have added the baseline methods, thanks
