### ISSUE TITLE
Why does the loss function become negative？

### ISSUE THREAD

**Issue by haterbreaker** [mohamedr002/MAPU_SFDA_TS#2]
When using HAR dataset, I noticed that the entropy_loss and total loss will become negative in adaptation stage. What does it mean when loss goes negative？

**Comment by mohamedr002** [comment]
@haterbreaker, thanks for raising this. To clarify, a negative loss is not indicative of a problem. In loss function optimization, the goal is to reduce its gradient. A smaller loss—whether it's less positive or more negative—typically signifies improved predictions. In other words, the absolute value of the loss is secondary; what's vital is the gradient, guiding how model parameters should be adjusted.  Regarding intuition, the reason for the negative values in our approach: we subtract the IM loss from the entropy loss, leading to negative results in certain instances.

**Comment by haterbreaker** [comment]
Thanks for your answer
